using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mokk.Generator;

[Generator]
public class MockGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Mokk.GenerateMockAttribute",
                predicate: static (node, _) => node is CompilationUnitSyntax,
                transform: static (ctx, _) => GetTargets(ctx))
            .SelectMany(static (x, _) => x);

        // The C#14 `extension` factory only compiles when the *consumer's*
        // language version is C# 14+. Detect it from parse options rather than
        // the target framework (a net10 project can still pin LangVersion 12).
        var supportsExtensions = context.ParseOptionsProvider.Select(static (po, _) =>
            po is CSharpParseOptions cs
            && (int)cs.LanguageVersion.MapSpecifiedToEffectiveVersion() >= 1400);

        context.RegisterSourceOutput(allTargets.Combine(supportsExtensions), static (spc, pair) =>
        {
            var (symbol, emitFactory) = pair;
            if (symbol.TypeKind == TypeKind.Interface)
                Execute(spc, symbol, emitFactory);
            else
                ExecuteAbstractClass(spc, symbol, emitFactory);
        });
    }

    private static ImmutableArray<INamedTypeSymbol> GetTargets(GeneratorAttributeSyntaxContext context)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        foreach (var attr in context.Attributes)
        {
            if (attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is INamedTypeSymbol symbol
                && (symbol.TypeKind == TypeKind.Interface || (symbol.TypeKind == TypeKind.Class && symbol.IsAbstract)))
            {
                // Collapse unbound and closed generics to the open definition (IMessage<T, U>).
                builder.Add(symbol.OriginalDefinition);
            }
        }
        return builder.ToImmutable();
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol interfaceSymbol, bool emitFactory)
    {
        var interfaceName = interfaceSymbol.Name;
        var ns = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : interfaceSymbol.ContainingNamespace.ToDisplayString();

        var mockClassName = GetMockClassName(interfaceName);
        var generics = GetGenericInfo(interfaceSymbol);
        var qualifiedInterface = interfaceSymbol.ToDisplayString(TypeFormat);
        var members = CollectMembers(interfaceSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Mokk;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        EmitMockClass(sb, mockClassName, qualifiedInterface, members, generics);
        if (emitFactory)
            EmitFactoryExtension(sb, qualifiedInterface, mockClassName, generics, isInterface: true);

        var fileName = ns != null ? $"{ns}.{mockClassName}" : mockClassName;
        if (generics.Arity > 0)
            fileName += $"_{generics.Arity}";
        context.AddSource($"{fileName}.g.cs", sb.ToString());
    }

    private static string GetMockClassName(string typeName)
    {
        const int abstractPrefixLength = 8; // "Abstract".Length
        string baseName;
        if (typeName.StartsWith("Abstract") && typeName.Length > abstractPrefixLength && char.IsUpper(typeName[abstractPrefixLength]))
            baseName = typeName.Substring(abstractPrefixLength);
        else if (typeName.Length > 1 && typeName[0] == 'I' && char.IsUpper(typeName[1]))
            baseName = typeName.Substring(1);
        else
            baseName = typeName;
        return $"Mock{baseName}";
    }

    private readonly struct GenericInfo(string typeParams, string constraints, int arity)
    {
        public string TypeParams { get; } = typeParams;   // "<T, U>" or ""
        public string Constraints { get; } = constraints;  // " where T : class ..." or ""
        public int Arity { get; } = arity;
    }

    private static GenericInfo GetGenericInfo(INamedTypeSymbol symbol)
    {
        var tps = symbol.TypeParameters;
        if (tps.Length == 0)
            return new GenericInfo("", "", 0);

        var typeParams = $"<{string.Join(", ", tps.Select(tp => tp.Name))}>";

        var clauses = new StringBuilder();
        foreach (var tp in tps)
        {
            var parts = new List<string>();

            if (tp.HasReferenceTypeConstraint) parts.Add("class");
            else if (tp.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
            else if (tp.HasValueTypeConstraint) parts.Add("struct");
            else if (tp.HasNotNullConstraint) parts.Add("notnull");

            foreach (var ct in tp.ConstraintTypes)
                parts.Add(ct.ToDisplayString(TypeFormat));

            if (tp.HasConstructorConstraint && !tp.HasValueTypeConstraint && !tp.HasUnmanagedTypeConstraint)
                parts.Add("new()");

            if (parts.Count > 0)
                clauses.Append($" where {tp.Name} : {string.Join(", ", parts)}");
        }

        return new GenericInfo(typeParams, clauses.ToString(), tps.Length);
    }

    private static MemberCollection CollectMembers(INamedTypeSymbol interfaceSymbol)
    {
        var methods = new List<MethodModel>();
        var properties = new List<PropertyModel>();
        var events = new List<EventModel>();
        var indexers = new List<IndexerModel>();
        var forwards = new List<ExplicitForwardModel>();
        var rawMethods = new List<IMethodSymbol>();
        var seen = new HashSet<string>();

        void Process(INamedTypeSymbol iface)
        {
            foreach (var member in iface.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method:
                    {
                        rawMethods.Add(method);
                        break;
                    }
                    case IPropertySymbol { IsIndexer: true } indexer:
                    {
                        if (seen.Add(IndexerKey(indexer)))
                        {
                            indexers.Add(IndexerModel.From(indexer));
                        }

                        break;
                    }
                    case IPropertySymbol prop:
                    {
                        if (seen.Add($"p:{prop.Name}"))
                        {
                            properties.Add(PropertyModel.From(prop));
                        }

                        break;
                    }
                    case IEventSymbol ev:
                    {
                        if (seen.Add($"e:{ev.Name}"))
                        {
                            events.Add(EventModel.From(ev));
                        }

                        break;
                    }
                }
            }
        }

        Process(interfaceSymbol);
        foreach (var baseInterface in interfaceSymbol.AllInterfaces)
            Process(baseInterface);

        // Methods that share a name and parameters but differ in return type
        // (the IEnumerable<T> / IEnumerable.GetEnumerator pair) can't all be
        // implemented implicitly: C# binds one implicit method to one slot, so
        // the most-derived return becomes the real method and every other slot
        // gets an explicit interface implementation that just forwards to it.
        foreach (var group in rawMethods.GroupBy(MethodSignatureKey))
        {
            var siblings = group.ToList();
            var primary = siblings.FirstOrDefault(c =>
                siblings.All(o => ReturnAssignable(c.ReturnType, o.ReturnType))) ?? siblings[0];
            methods.Add(MethodModel.From(primary));

            foreach (var sibling in siblings)
                if (!SymbolEqualityComparer.Default.Equals(sibling.ReturnType, primary.ReturnType)
                    && ReturnAssignable(primary.ReturnType, sibling.ReturnType))
                    forwards.Add(ExplicitForwardModel.From(sibling));
        }

        return new MemberCollection(methods, properties, events, indexers, forwards);
    }

    private static string FormatParamType(IEnumerable<IParameterSymbol> ps)
        => string.Join(",", ps.Select(p => p.Type.ToDisplayString(TypeFormat)));

    private static string MethodSignatureKey(IMethodSymbol m)
        => $"{m.Name}({FormatParamType(m.Parameters)})";

    // True when a value of type `from` can satisfy a `to` return slot, i.e.
    // `from` is `to`, derives from it, or implements it.
    private static bool ReturnAssignable(ITypeSymbol from, ITypeSymbol to)
    {
        if (SymbolEqualityComparer.Default.Equals(from, to))
            return true;
        if (from.AllInterfaces.Contains(to, SymbolEqualityComparer.Default))
            return true;
        for (var b = from.BaseType; b is not null; b = b.BaseType)
            if (SymbolEqualityComparer.Default.Equals(b, to))
                return true;
        return false;
    }

    // Indexers all share the name "this[]", so dedupe across the inheritance
    // chain by parameter types (overloaded indexers are kept separate).
    private static string IndexerKey(IPropertySymbol s)
        => $"i:({FormatParamType(s.Parameters)})";

    private static void EmitVerifyInOrder(StringBuilder sb, string interceptorRef, string indent)
    {
        var i = indent;
        sb.AppendLine($"{i}public void VerifyInOrder(params ICallSpec[] steps)");
        sb.AppendLine($"{i}{{");
        sb.AppendLine($"{i}    var parsed = new (string, System.Type[]?, IMatcher[])[steps.Length];");
        sb.AppendLine($"{i}    for (int si = 0; si < steps.Length; si++)");
        sb.AppendLine($"{i}        parsed[si] = (steps[si].Method, steps[si].TypeArgs, steps[si].Matchers);");
        sb.AppendLine($"{i}    {interceptorRef}.VerifyInOrder(parsed);");
        sb.AppendLine($"{i}}}");
    }

    // Setup-handle parameters: out params are produced by the mock, not matched,
    // so they're dropped from the handle signature and treated as wildcards.
    private static string MatcherParamList(IReadOnlyList<ParameterModel> ps)
        => string.Join(", ", ps.Where(p => !p.IsOut).Select(p => $"Matcher<{p.Type}> {p.Name}"));

    private static string MatcherArrayExpr(IReadOnlyList<ParameterModel> ps)
        => ps.Count == 0
            ? "Array.Empty<IMatcher>()"
            : $"new IMatcher[] {{ {string.Join(", ", ps.Select(p => p.IsOut ? $"Matcher<{p.Type}>.Any.Inner" : $"{p.Name}.Inner"))} }}";

    private static string HandleMatcherParams(MethodModel m) => MatcherParamList(m.Parameters);
    private static string HandleMatchersExpr(MethodModel m) => MatcherArrayExpr(m.Parameters);

    private static string TypeArgsExpr(MethodModel m)
        => m.TypeParameterNames.Count > 0
            ? $"new System.Type[] {{ {string.Join(", ", m.TypeParameterNames.Select(tp => $"typeof({tp})"))} }}"
            : "null";

    private static string TypeParamList(MethodModel m)
        => m.TypeParameterNames.Count > 0 ? $"<{string.Join(", ", m.TypeParameterNames)}>" : "";

    // Setup accessor: `Indexer(Matcher<int> i)` → IndexerHandle keyed on the
    // indexer's metadata name. Emitted on the mock for both interfaces and
    // abstract classes (a method, so it never clashes with an overridden
    // `this[...]` the way a property handle would clash with its property).
    private static void EmitIndexerSetupAccessor(StringBuilder sb, string indent, IndexerModel x)
    {
        sb.AppendLine($"{indent}public IndexerHandle<{x.ValueType}> Indexer({MatcherParamList(x.Parameters)})");
        sb.AppendLine($"{indent}    => new(_interceptor, \"{x.MetadataName}\", {MatcherArrayExpr(x.Parameters)});");
        sb.AppendLine();
    }

    // The real `this[...]` member that satisfies the interface/base type,
    // forwarding to the interceptor as get_/set_<MetadataName>.
    private static void EmitIndexerImpl(StringBuilder sb, string indent, string prefix, IndexerModel x)
    {
        var sig = string.Join(", ", x.Parameters.Select(p => $"{p.Type} {p.Name}"));
        var indexArgs = string.Join(", ", x.Parameters.Select(p => p.Name));
        sb.AppendLine($"{indent}{prefix} {x.ValueType} this[{sig}]");
        sb.AppendLine($"{indent}{{");
        if (x.HasGetter)
            sb.AppendLine($"{indent}    get => _interceptor.Intercept<{x.ValueType}>(\"get_{x.MetadataName}\", null, new object?[] {{ {indexArgs} }});");
        if (x.HasSetter)
            sb.AppendLine($"{indent}    set => _interceptor.InterceptVoid(\"set_{x.MetadataName}\", null, new object?[] {{ {indexArgs}, value }});");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    // Emits a method that forwards to the interceptor. ref/out parameters require a
    // statement body so their values can be copied back from the (possibly mutated)
    // args array after the call.
    private static void EmitInterceptedMethod(StringBuilder sb, string indent, string prefix, MethodModel m)
    {
        var typeParams = TypeParamList(m);
        var typeArgs = TypeArgsExpr(m);
        var sig = string.Join(", ", m.Parameters.Select(p => $"{p.Modifier}{p.Type} {p.Name}"));
        var argsLiteral = m.Parameters.Count > 0
            ? $"new object?[] {{ {string.Join(", ", m.Parameters.Select(p => p.IsOut ? $"default({p.Type})" : p.Name))} }}"
            : "Array.Empty<object?>()";
        var ret = m.IsVoid ? "void" : m.ReturnType;

        if (!m.Parameters.Any(p => p.WritesBack))
        {
            sb.AppendLine($"{indent}{prefix} {ret} {m.Name}{typeParams}({sig})");
            sb.AppendLine(m.IsVoid
                ? $"{indent}    => _interceptor.InterceptVoid(\"{m.Name}\", {typeArgs}, {argsLiteral});"
                : $"{indent}    => _interceptor.Intercept<{m.ReturnType}>(\"{m.Name}\", {typeArgs}, {argsLiteral});");
            sb.AppendLine();
            return;
        }

        sb.AppendLine($"{indent}{prefix} {ret} {m.Name}{typeParams}({sig})");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var __args = {argsLiteral};");
        sb.AppendLine(m.IsVoid
            ? $"{indent}    _interceptor.InterceptVoid(\"{m.Name}\", {typeArgs}, __args);"
            : $"{indent}    var __ret = _interceptor.Intercept<{m.ReturnType}>(\"{m.Name}\", {typeArgs}, __args);");
        for (int idx = 0; idx < m.Parameters.Count; idx++)
        {
            var p = m.Parameters[idx];
            if (p.WritesBack)
                sb.AppendLine($"{indent}    {p.Name} = ({p.Type})__args[{idx}]!;");
        }
        if (!m.IsVoid)
            sb.AppendLine($"{indent}    return __ret;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    // C# 14 static extension members let `IFoo.Mock()` work without the user
    // declaring their type partial. Only emitted when the consumer compiles with
    // C# 14+ (detected from parse options), so older toolchains never see it.
    private static void EmitFactoryExtension(
        StringBuilder sb, string qualifiedType, string mockClassName, GenericInfo generics, bool isInterface)
    {
        var mockType = $"{mockClassName}{generics.TypeParams}";
        var ctorParams = isInterface
            ? $"bool strict = false, {qualifiedType}? wrapping = null, System.Action<string>? onUnusedSetup = null"
            : "bool strict = false, System.Action<string>? onUnusedSetup = null";
        var ctorArgs = isInterface ? "strict, wrapping, onUnusedSetup" : "strict, onUnusedSetup";

        sb.AppendLine();
        sb.AppendLine("public static partial class MokkFactories");
        sb.AppendLine("{");
        sb.AppendLine($"    extension{generics.TypeParams}({qualifiedType}){generics.Constraints}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static {mockType} Mock({ctorParams}) => new({ctorArgs});");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitMockClass(
        StringBuilder sb, string className, string qualifiedInterface, MemberCollection members, GenericInfo generics)
    {
        sb.AppendLine($"public sealed class {className}{generics.TypeParams} : global::Mokk.IMockObject{generics.Constraints}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly MockInterceptor _interceptor;");
        sb.AppendLine($"    private readonly __Instance _inner;");
        sb.AppendLine($"    public {qualifiedInterface} Instance => _inner;");
        sb.AppendLine($"    global::Mokk.MockInterceptor global::Mokk.IMockObject.Interceptor => _interceptor;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(bool strict = false, {qualifiedInterface}? wrapping = null, System.Action<string>? onUnusedSetup = null)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        _interceptor = new(strict, wrapping, typeof({qualifiedInterface}), onUnusedSetup);");
        sb.AppendLine($"        _inner = new(_interceptor);");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    public void Reset() {{ _interceptor.Reset(); _inner.ResetState(); }}");
        sb.AppendLine($"    public void CheckUnusedSetups() => _interceptor.CheckUnusedSetups();");
        sb.AppendLine($"    public void VerifyNoOtherCalls() => _interceptor.VerifyNoOtherCalls();");
        sb.AppendLine();

        foreach (var m in members.Methods)
        {
            var typeParams = TypeParamList(m);
            var matcherParms = HandleMatcherParams(m);
            var typeArgsExpr = TypeArgsExpr(m);
            var matchersExpr = HandleMatchersExpr(m);

            if (m.IsVoid)
            {
                sb.AppendLine($"    public VoidMethodHandle {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"        => new(_interceptor, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            else
            {
                sb.AppendLine($"    public MethodHandle<{m.ReturnType}> {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"        => new(_interceptor, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            sb.AppendLine();
        }

        foreach (var p in members.Properties)
        {
            sb.AppendLine($"    public PropertyHandle<{p.Type}> {p.Name} => new(_interceptor, \"{p.Name}\");");
            sb.AppendLine();
        }

        foreach (var e in members.Events)
        {
            sb.AppendLine($"    public EventHandle {e.Name} => new(_interceptor, \"{e.Name}\");");
            sb.AppendLine();
        }

        foreach (var x in members.Indexers)
            EmitIndexerSetupAccessor(sb, "    ", x);

        EmitVerifyInOrder(sb, "_interceptor", indent: "    ");
        sb.AppendLine();
        EmitInstanceClass(sb, qualifiedInterface, members, indent: "    ");
        sb.AppendLine("}");
    }

    private static void EmitInstanceClass(
        StringBuilder sb, string qualifiedInterface, MemberCollection members, string indent)
    {
        var i = indent;
        var ii = indent + "    ";

        sb.AppendLine($"{i}private sealed class __Instance : {qualifiedInterface}");
        sb.AppendLine($"{i}{{");
        sb.AppendLine($"{ii}private readonly MockInterceptor _interceptor;");

        var settableProps = members.Properties.Where(p => p.HasSetter).ToList();
        foreach (var p in settableProps)
        {
            sb.AppendLine($"{ii}private {p.Type}? _backing_{p.Name};");
            sb.AppendLine($"{ii}private bool _backing_{p.Name}_set;");
        }
        sb.AppendLine();
        sb.AppendLine($"{ii}internal __Instance(MockInterceptor interceptor) => _interceptor = interceptor;");
        sb.AppendLine();

        if (settableProps.Count > 0)
        {
            sb.AppendLine($"{ii}internal void ResetState()");
            sb.AppendLine($"{ii}{{");
            foreach (var p in settableProps)
            {
                sb.AppendLine($"{ii}    _backing_{p.Name} = default;");
                sb.AppendLine($"{ii}    _backing_{p.Name}_set = false;");
            }
            sb.AppendLine($"{ii}}}");
        }
        else
        {
            sb.AppendLine($"{ii}internal void ResetState() {{ }}");
        }
        sb.AppendLine();

        foreach (var m in members.Methods)
            EmitInterceptedMethod(sb, ii, "public", m);

        foreach (var p in members.Properties)
        {
            sb.AppendLine($"{ii}public {p.Type} {p.Name}");
            sb.AppendLine($"{ii}{{");
            if (p.HasGetter)
            {
                if (p.HasSetter)
                    sb.AppendLine($"{ii}    get => _backing_{p.Name}_set ? _backing_{p.Name}! : _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
                else
                    sb.AppendLine($"{ii}    get => _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
            }
            if (p.HasSetter)
                sb.AppendLine($"{ii}    set {{ _backing_{p.Name}_set = true; _backing_{p.Name} = value; _interceptor.InterceptVoid(\"set_{p.Name}\", null, new object?[] {{ value }}); }}");
            sb.AppendLine($"{ii}}}");
            sb.AppendLine();
        }

        foreach (var e in members.Events)
        {
            sb.AppendLine($"{ii}public event {e.HandlerType} {e.Name}");
            sb.AppendLine($"{ii}{{");
            sb.AppendLine($"{ii}    add => _interceptor.AddEventHandler(\"{e.Name}\", value);");
            sb.AppendLine($"{ii}    remove => _interceptor.RemoveEventHandler(\"{e.Name}\", value);");
            sb.AppendLine($"{ii}}}");
            sb.AppendLine();
        }

        foreach (var x in members.Indexers)
            EmitIndexerImpl(sb, ii, "public", x);

        // Explicitly implement covariant-return siblings (e.g. the non-generic
        // IEnumerable.GetEnumerator) by forwarding to the implicit method.
        foreach (var f in members.ExplicitForwards)
        {
            var sig = string.Join(", ", f.Parameters.Select(p => $"{p.Modifier}{p.Type} {p.Name}"));
            var args = string.Join(", ", f.Parameters.Select(p => $"{p.Modifier}{p.Name}"));
            sb.AppendLine($"{ii}{f.ReturnType} {f.InterfaceType}.{f.Name}({sig}) => this.{f.Name}({args});");
            sb.AppendLine();
        }

        sb.AppendLine($"{i}}}");
    }

    private static void ExecuteAbstractClass(SourceProductionContext context, INamedTypeSymbol classSymbol, bool emitFactory)
    {
        var className = classSymbol.Name;
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var mockClassName = GetMockClassName(className);
        var generics = GetGenericInfo(classSymbol);
        var qualifiedClass = classSymbol.ToDisplayString(TypeFormat);
        var members = CollectAbstractClassMembers(classSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Mokk;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        EmitAbstractClassMock(sb, mockClassName, qualifiedClass, members, generics);
        if (emitFactory)
            EmitFactoryExtension(sb, qualifiedClass, mockClassName, generics, isInterface: false);

        var fileName = ns != null ? $"{ns}.{mockClassName}" : mockClassName;
        if (generics.Arity > 0)
            fileName += $"_{generics.Arity}";
        context.AddSource($"{fileName}.g.cs", sb.ToString());
    }

    private static MemberCollection CollectAbstractClassMembers(INamedTypeSymbol classSymbol)
    {
        var methods = new List<MethodModel>();
        var properties = new List<PropertyModel>();
        var events = new List<EventModel>();
        var indexers = new List<IndexerModel>();
        var seen = new HashSet<string>();

        INamedTypeSymbol? current = classSymbol;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method
                        when (method.IsAbstract || method.IsVirtual)
                          && method.DeclaredAccessibility != Accessibility.Private:
                    {
                        if (seen.Add("m:" + MethodSignatureKey(method)))
                            methods.Add(MethodModel.From(method));
                        break;
                    }
                    case IPropertySymbol { IsIndexer: true } indexer
                        when (indexer.IsAbstract || indexer.IsVirtual)
                          && indexer.DeclaredAccessibility != Accessibility.Private:
                    {
                        if (seen.Add(IndexerKey(indexer)))
                            indexers.Add(IndexerModel.From(indexer));
                        break;
                    }
                    case IPropertySymbol prop
                        when (prop.IsAbstract || prop.IsVirtual)
                          && prop.DeclaredAccessibility != Accessibility.Private:
                    {
                        if (seen.Add($"p:{prop.Name}"))
                            properties.Add(PropertyModel.From(prop));
                        break;
                    }
                    case IEventSymbol ev
                        when (ev.IsAbstract || ev.IsVirtual)
                          && ev.DeclaredAccessibility != Accessibility.Private:
                    {
                        if (seen.Add($"e:{ev.Name}"))
                            events.Add(EventModel.From(ev));
                        break;
                    }
                }
            }
            current = current.BaseType;
        }

        return new MemberCollection(methods, properties, events, indexers);
    }

    private static void EmitAbstractClassMock(
        StringBuilder sb, string className, string qualifiedClass, MemberCollection members, GenericInfo generics)
    {
        sb.AppendLine($"public sealed class {className}{generics.TypeParams} : {qualifiedClass}, global::Mokk.IMockObject{generics.Constraints}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly MockInterceptor _interceptor;");
        sb.AppendLine($"    public {qualifiedClass} Instance => this;");
        sb.AppendLine($"    global::Mokk.MockInterceptor global::Mokk.IMockObject.Interceptor => _interceptor;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(bool strict = false, System.Action<string>? onUnusedSetup = null) : base()");
        sb.AppendLine($"        => _interceptor = new(strict, null, typeof({qualifiedClass}), onUnusedSetup);");
        sb.AppendLine();
        sb.AppendLine("    public void Reset() => _interceptor.Reset();");
        sb.AppendLine("    public void CheckUnusedSetups() => _interceptor.CheckUnusedSetups();");
        sb.AppendLine("    public void VerifyNoOtherCalls() => _interceptor.VerifyNoOtherCalls();");
        sb.AppendLine();

        foreach (var m in members.Methods)
            EmitInterceptedMethod(sb, "    ", $"{(m.IsProtected ? "protected" : "public")} override", m);

        var settableProps = members.Properties.Where(p => p.HasSetter).ToList();
        foreach (var p in settableProps)
        {
            sb.AppendLine($"    private {p.Type}? _backing_{p.Name};");
            sb.AppendLine($"    private bool _backing_{p.Name}_set;");
        }
        if (settableProps.Count > 0)
            sb.AppendLine();

        foreach (var p in members.Properties)
        {
            var access = p.IsProtected ? "protected" : "public";
            sb.AppendLine($"    {access} override {p.Type} {p.Name}");
            sb.AppendLine("    {");
            if (p.HasGetter)
            {
                if (p.HasSetter)
                    sb.AppendLine($"        get => _backing_{p.Name}_set ? _backing_{p.Name}! : _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
                else
                    sb.AppendLine($"        get => _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
            }
            if (p.HasSetter)
                sb.AppendLine($"        set {{ _backing_{p.Name}_set = true; _backing_{p.Name} = value; _interceptor.InterceptVoid(\"set_{p.Name}\", null, new object?[] {{ value }}); }}");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var e in members.Events)
        {
            var access = e.IsProtected ? "protected" : "public";
            sb.AppendLine($"    {access} override event {e.HandlerType} {e.Name}");
            sb.AppendLine("    {");
            sb.AppendLine($"        add => _interceptor.AddEventHandler(\"{e.Name}\", value);");
            sb.AppendLine($"        remove => _interceptor.RemoveEventHandler(\"{e.Name}\", value);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var x in members.Indexers)
            EmitIndexerImpl(sb, "    ", $"{(x.IsProtected ? "protected" : "public")} override", x);

        EmitAbstractClassShortcuts(sb, "_interceptor", members, indent: "    ");
        EmitVerifyInOrder(sb, "_interceptor", indent: "    ");
        sb.AppendLine("}");
    }

    private static void EmitAbstractClassShortcuts(
        StringBuilder sb, string interceptorRef, MemberCollection members, string indent)
    {
        var i = indent;

        foreach (var m in members.Methods)
        {
            // Zero-parameter shortcuts can't be added: the override already occupies the same signature
            if (m.Parameters.Count == 0)
                continue;

            var typeParams = TypeParamList(m);
            var matcherParms = HandleMatcherParams(m);
            var typeArgsExpr = TypeArgsExpr(m);
            var matchersExpr = HandleMatchersExpr(m);

            if (m.IsVoid)
            {
                sb.AppendLine($"{i}public VoidMethodHandle {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"{i}    => new({interceptorRef}, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            else
            {
                sb.AppendLine($"{i}public MethodHandle<{m.ReturnType}> {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"{i}    => new({interceptorRef}, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            sb.AppendLine();
        }

        // Property handles use "{Name}Handle" since the mock IS the class and can't reuse the property name
        foreach (var p in members.Properties)
        {
            sb.AppendLine($"{i}public PropertyHandle<{p.Type}> {p.Name}Handle => new({interceptorRef}, \"{p.Name}\");");
            sb.AppendLine();
        }

        // Event handles use "{Name}Handle" for the same reason: the mock IS the class
        foreach (var e in members.Events)
        {
            sb.AppendLine($"{i}public EventHandle {e.Name}Handle => new({interceptorRef}, \"{e.Name}\");");
            sb.AppendLine();
        }

        // The indexer setup accessor is a method named `Indexer`, so unlike
        // property handles it doesn't collide with the overridden `this[...]`.
        foreach (var x in members.Indexers)
            EmitIndexerSetupAccessor(sb, i, x);
    }

    private class MemberCollection(
        List<MethodModel> methods, List<PropertyModel> properties,
        List<EventModel> events, List<IndexerModel> indexers,
        List<ExplicitForwardModel>? forwards = null)
    {
        public List<MethodModel> Methods { get; } = methods;
        public List<PropertyModel> Properties { get; } = properties;
        public List<EventModel> Events { get; } = events;
        public List<IndexerModel> Indexers { get; } = indexers;
        public List<ExplicitForwardModel> ExplicitForwards { get; } = forwards ?? new();
    }

    private class MethodModel
    {
        public string Name { get; private set; } = "";
        public string ReturnType { get; private set; } = "";
        public bool IsVoid { get; private set; }
        public bool IsProtected { get; private set; }
        public List<ParameterModel> Parameters { get; private set; } = new();
        public List<string> TypeParameterNames { get; private set; } = new();

        public static MethodModel From(IMethodSymbol s) => new()
        {
            Name = s.Name,
            IsVoid = s.ReturnsVoid,
            ReturnType = s.ReturnType.ToDisplayString(TypeFormat),
            Parameters = s.Parameters.Select(ParameterModel.From).ToList(),
            TypeParameterNames = s.TypeParameters.Select(tp => tp.Name).ToList(),
            IsProtected = IsProtectedAccess(s),
        };
    }

    private static bool IsProtectedAccess(ISymbol s)
        => s.DeclaredAccessibility is Accessibility.Protected or Accessibility.ProtectedAndInternal;

    private class ParameterModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";
        public string Modifier { get; private set; } = "";  // "", "ref ", "out ", "in ", "ref readonly "
        public bool IsOut { get; private set; }
        public bool WritesBack { get; private set; }         // out or ref: value must be copied back

        public static ParameterModel From(IParameterSymbol s)
        {
            var (modifier, isOut, writesBack) = s.RefKind switch
            {
                RefKind.Out => ("out ", true, true),
                RefKind.Ref => ("ref ", false, true),
                RefKind.In => ("in ", false, false),
                RefKind.RefReadOnlyParameter => ("ref readonly ", false, false),
                _ => ("", false, false),
            };
            return new()
            {
                Name = s.Name,
                Type = s.Type.ToDisplayString(TypeFormat),
                Modifier = modifier,
                IsOut = isOut,
                WritesBack = writesBack,
            };
        }
    }

    private class PropertyModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";
        public bool HasGetter { get; private set; }
        public bool HasSetter { get; private set; }
        public bool IsProtected { get; private set; }

        public static PropertyModel From(IPropertySymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
            HasGetter = !s.IsWriteOnly,
            HasSetter = !s.IsReadOnly,
            IsProtected = IsProtectedAccess(s),
        };
    }

    private class EventModel
    {
        public string Name { get; private set; } = "";
        public string HandlerType { get; private set; } = "";
        public bool IsProtected { get; private set; }

        public static EventModel From(IEventSymbol s) => new()
        {
            Name = s.Name,
            HandlerType = s.Type.ToDisplayString(TypeFormat),
            IsProtected = IsProtectedAccess(s),
        };
    }

    // An indexer is an IPropertySymbol with IsIndexer == true. Its accessors are
    // emitted as get_/set_<MetadataName> ("Item" by default), so it behaves like
    // a method pair whose arguments are the index parameters.
    private class IndexerModel
    {
        public string MetadataName { get; private set; } = "Item";
        public string ValueType { get; private set; } = "";
        public bool HasGetter { get; private set; }
        public bool HasSetter { get; private set; }
        public bool IsProtected { get; private set; }
        public List<ParameterModel> Parameters { get; private set; } = new();

        public static IndexerModel From(IPropertySymbol s) => new()
        {
            MetadataName = s.MetadataName,
            ValueType = s.Type.ToDisplayString(TypeFormat),
            HasGetter = !s.IsWriteOnly,
            HasSetter = !s.IsReadOnly,
            IsProtected = IsProtectedAccess(s),
            Parameters = s.Parameters.Select(ParameterModel.From).ToList(),
        };
    }

    // A method shadowed by a covariant-return collision, implemented explicitly
    // and forwarded to the implicit (most-derived) sibling so both interface
    // slots are satisfied with one interception point.
    private class ExplicitForwardModel
    {
        public string InterfaceType { get; private set; } = "";
        public string ReturnType { get; private set; } = "";
        public string Name { get; private set; } = "";
        public List<ParameterModel> Parameters { get; private set; } = new();

        public static ExplicitForwardModel From(IMethodSymbol s) => new()
        {
            InterfaceType = s.ContainingType.ToDisplayString(TypeFormat),
            ReturnType = s.ReturnType.ToDisplayString(TypeFormat),
            Name = s.Name,
            Parameters = s.Parameters.Select(ParameterModel.From).ToList(),
        };
    }
}
